name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/main.yml
    with:
      buildFlags: officialBuild

  release-windows:
    name: Release windowsBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        path: build
        name: windowsBuild
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip build.zip -w ./build/.
    - name: Upload windowsBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: FNF-JS-Engine.zip
        overwrite: false

  release-android:
    name: Release androidBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Android artifact
      uses: actions/download-artifact@v3
      with:
        path: build
        name: androidBuild
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip build.zip -w ./build/.
    - name: Upload Android build to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: FNF-JS-Engine-Android.zip
        overwrite: false

  release-mac:
    name: Release macBuild
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Mac artifact
      uses: actions/download-artifact@v3
      with:
        path: build
        name: macBuild
    - name: Compress build
      run: |
        sudo apt-get install p7zip-full
        7z a -tzip build.zip -w ./build/.
    - name: Upload macBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: FNF-JS-Engine-macOS.zip
        overwrite: false
